---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ptrapr)
library(ggraph)
library(magrittr)
library(igraph)
library(tibble)
library(dplyr)
library(tidygraph)
```


```{r}
path <- system.file("extdata/Nip_1_1_6307.ricepr", 
                   package = "ptrapr") 

panicle <-
  path %>% 
  read_panicle()
```


```{r}
panicle %>% 
  ggraph() + 
  geom_edge_link(arrow = grid::arrow(length = unit(0.08,
                                                   "inches"),
                                     type = "closed"),
                 colour = "grey30") +
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
```

```{r}
panicle %>% 
  ggraph(layout = "dendrogram") + 
  geom_edge_diagonal()+
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
```

```{r}
grain_path <- system.file("extdata/Nip_1_1_6307.ricegr",
                          package = "ptrapr")

grains <- 
  grain_path %>%
  read_grain()
  
```

```{r}
new_graph <- 
  panicle %>%
  add_grain()
```


```{r}
new_graph %>% 
  ggraph() + 
  geom_edge_link(arrow = grid::arrow(length = unit(0.08,
                                                   "inches"),
                                     type = "closed"),
                 colour = "grey30") +
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
```

```{r}
full_graph <- 
  panicle %>% 
  add_all_grains(grains)
```

```{r}
full_graph %>% 
  ggraph() + 
  geom_edge_link(arrow = grid::arrow(length = unit(0.08,
                                                   "inches"),
                                     type = "closed"),
                 colour = "grey30") +
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
```


# test another panicle

```{r}
path <- system.file("extdata/Nip_1_2_6308.ricepr", 
                   package = "ptrapr") 

panicle2 <-
  path %>% 
  read_panicle()
```


```{r}
panicle2 %>% 
  ggraph() + 
  geom_edge_link(arrow = grid::arrow(length = unit(0.08,
                                                   "inches"),
                                     type = "closed"),
                 colour = "grey30") +
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
```


# igraph Reminder

type

```{r}
panicle %>% 
  vertex_attr()

panicle %>% 
  vertex_attr(name = "type")

panicle %>%
  edge_attr()

panicle %>% 
  as_long_data_frame() %>%
  filter(from_type == "Primary",
         to_type == "Primary") %>%
```


children

```{r}
panicle %>%
  neighbors(1, "out")
```

```{r}

```

graph to dataframe

```{r}
panicle %>% 
  as_long_data_frame() %>%
  as_tibble()
```

# Manipulate with tidygraph?

```{r}
library(tidygraph)
```

```{r}
panicle2

panicle2 %>%
  activate(edges) %>%
  reroute(from = to, to = from) %>%
  ggraph() + 
  geom_edge_link(arrow = grid::arrow(length = unit(0.08,
                                                   "inches"),
                                     type = "closed"),
                 colour = "grey30") +
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
```

```{r}
prim_gen <- 
  panicle2 %>% 
  as_long_data_frame() %>%
  filter(from_type %in% c("Primary", "Generating"),
         to_type %in% c("Primary", "Generating")) %>%
  select(from, to)


panicle2 %>%
  as_tbl_graph() %>%
  activate(edges) %>%
  active()
  
# use reroute and case_when
panicle2 %>%
  as_tbl_graph() %>% 
  activate(edges) %>%
  reroute(from = case_when(from %in% prim_gen$from & 
                             to %in% prim_gen$to ~ to,
                           TRUE ~ from),
          to = case_when(from %in% prim_gen$from &
                           to %in% prim_gen$to ~ from,
                         TRUE ~ to)) %>% 
  
  ggraph() + 
  geom_edge_link(arrow = grid::arrow(length = unit(0.08,
                                                   "inches"),
                                     type = "closed"),
                 colour = "grey30") +
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
  

# am I using from and to correctly?

panicle2 %>%
  as_long_data_frame() %>%
  filter(from_type == "Generating")
```

# Reproduce Helene's plot

```{r}
prim_gen <- 
  full_graph %>% 
  as_long_data_frame() %>%
  filter(from_type %in% c("Primary", "Generating"),
         to_type %in% c("Primary", "Generating")) %>%
  select(from, to)

tst <- 
  full_graph %>%
  as_tbl_graph() %>% 
  activate(edges) %>%
  reroute(from = case_when(from %in% prim_gen$from & 
                             to %in% prim_gen$to ~ to,
                           TRUE ~ from),
          to = case_when(from %in% prim_gen$from &
                           to %in% prim_gen$to ~ from,
                         TRUE ~ to)) 

tst %>% 
  ggraph() + 
  geom_edge_link(arrow = grid::arrow(length = unit(0.08,
                                                   "inches"),
                                     type = "closed"),
                 colour = "grey30") +
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
```

```{r}
first_node <- 
  tst %>% 
  as_long_data_frame() %>%
  filter(from_type == "Generating") %>%
  filter(from_x == max(from_x)) %>%
  filter(to_type != "Primary")
```

```{r}
dot_plot <- 
  tibble(x = 1,
         y = 1,
         type = "secondary")


# select children with type "secondary"
tst %>%
  neighbors(first_node$from, mode = "out") 

  

# select children with type "secondary"
# second strategy
tst %>% 
  as_long_data_frame() %>%
  filter(from_type == "Generating") %>%
  filter(from_x == max(from_x)) %>%
  filter(to_type == "Seconday") %>%
  pull(to_rank)

# 21

# how do I find all descendants of a node?
first_subtree <- 
  tst %>% 
  subcomponent(21, mode = "out")
  
tst %>%
  induced.subgraph(first_subtree) %>%
  ggraph() + 
  geom_edge_link(arrow = grid::arrow(length = unit(0.08,
                                                   "inches"),
                                     type = "closed"),
                 colour = "grey30") +
  geom_node_point(aes(colour = type),
                  size = 2,
                  alpha =.7) +
  coord_fixed() +
  theme_minimal()
```

longest path - assume it is primary branch axis

```{r}
top_vertex <- 
  tst %>% 
  induced_subgraph(first_subtree) %>%
  # diameter(directed = TRUE) # 8
  distances(v = 1) %>%
  which.max()

f_subtree <-
  tst %>% 
  induced_subgraph(first_subtree)
```

```{r}
f_subtree %>% 
  vertex_attr()


f_node_rank <- 
f_subtree %>%
  shortest_paths(from = which(f_subtree %>%
                                vertex_attr() %>%
                                .$rank == first_node$to),
                 to = top_vertex)


```


```{r}
types <- f_subtree %>% vertex_attr() %$% type

types_ranked <- f_node_rank$vpath %>%
  purrr::flatten_int() %>%
  types[.]
```

```{r}
tibble(x = 1:length(types_ranked),
       y = 1,
       type = types_ranked) %>%
  ggplot(aes(x = x,
             y = y,
             colour = types_ranked)) +
  geom_point(size = 10) + 
  lims(y = c(0,2)) +
  theme_bw()
```

